package com.ahsan.domain;
// Generated Feb 4, 2016 3:37:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblArticle generated by hbm2java
 */
@Entity
@Table(name="tblArticle"
    ,schema="dbo"
    ,catalog="dbAhsan"
)
public class TblArticle  implements java.io.Serializable {


     private int id;
     private Integer pageDetailId;
     private String articleTitle;
     private String articleContent;

    public TblArticle() {
    }

	
    public TblArticle(int id) {
        this.id = id;
    }
    public TblArticle(int id, Integer pageDetailId, String articleTitle, String articleContent) {
       this.id = id;
       this.pageDetailId = pageDetailId;
       this.articleTitle = articleTitle;
       this.articleContent = articleContent;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="pageDetailId")
    public Integer getPageDetailId() {
        return this.pageDetailId;
    }
    
    public void setPageDetailId(Integer pageDetailId) {
        this.pageDetailId = pageDetailId;
    }

    
    @Column(name="articleTitle", length=50)
    public String getArticleTitle() {
        return this.articleTitle;
    }
    
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    
    @Column(name="articleContent", length=5000)
    public String getArticleContent() {
        return this.articleContent;
    }
    
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }




}


