package com.ahsan.domain;
// Generated Feb 4, 2016 3:37:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblPageDetail generated by hbm2java
 */
@Entity
@Table(name="tblPageDetail"
    ,schema="dbo"
    ,catalog="dbAhsan"
)
public class TblPageDetail  implements java.io.Serializable {


     private int id;
     private TblPageMaster tblPageMaster;
     private String pageName;

    public TblPageDetail() {
    }

	
    public TblPageDetail(int id) {
        this.id = id;
    }
    public TblPageDetail(int id, TblPageMaster tblPageMaster, String pageName) {
       this.id = id;
       this.tblPageMaster = tblPageMaster;
       this.pageName = pageName;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="masterPageId")
    public TblPageMaster getTblPageMaster() {
        return this.tblPageMaster;
    }
    
    public void setTblPageMaster(TblPageMaster tblPageMaster) {
        this.tblPageMaster = tblPageMaster;
    }

    
    @Column(name="pageName", length=10)
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }




}


